### ISSUE TITLE
Doesn't work for API level < 19

### ISSUE THREAD

**Issue by lepipele** [everalbum/roliedex#3]
The problem is that you are using constructor introduced only in API 19. Here is stack trace:

  Caused by: java.lang.NoSuchMethodError: android.widget.LinearLayout.<init>
    at com.everalbum.roliedex.RoliedexLayout.<init>(RoliedexLayout.java:67)
    at com.everalbum.roliedex.RoliedexLayout.<init>(RoliedexLayout.java:62)
    at com.everalbum.roliedex.RoliedexLayout.<init>(RoliedexLayout.java:58)
    at java.lang.reflect.Constructor.constructNative(Native Method) 
    at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
    at android.view.LayoutInflater.createView(LayoutInflater.java:587) 
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
    at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
    at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
    at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 

You can see this problem described on bunch of links:

https://www.google.com/search?q=Caused+by%3A+java.lang.NoSuchMethodError%3A+android.widget.LinearLayout.%3Cinit%3E&ie=utf-8&oe=utf-8
http://stackoverflow.com/questions/10644234/android-inflate-exception-on-custom-view

Thanks for great library

**Comment by lepipele** [comment]
OK, only now I've saw that you've released fix:

https://github.com/everalbum/roliedex/releases

You may consider [updating description on home page](https://github.com/everalbum/roliedex). I'll also see to fork and send pull request... need some features added.

**Comment by ralphpina** [comment]
@lepipele thanks for bringing this up. I'll update the page right now.

**Comment by lepipele** [comment]
@ralphpina Thanks for quick response and help
